### ISSUE TITLE
Segmentation Fault Caused by free() of Invalid Pointer

### ISSUE THREAD

**Issue by mxwli** [kuzudb/kuzu#2257]
By changing line 130 of create_tinysnb.test
`MATCH (a:person) WHERE a.ID > 8 RETURN a.ID, a.workedHours,a.usedNames`

to
`MATCH (a:person) WHERE a.ID > -1 RETURN a.ID, a.workedHours,a.usedNames`

you can reliably cause a segmentation fault from the freeing an invalid pointer. The test case itself is `TinySnbCreateNodeTest.InsertNodeWithListTest`

It's possible this bug has something to do with the fact that during the transaction in this test case, after the new node is created, it assumes that the new node is already compressed. A result that I noticed is that a call to CompressionAlg::decompressFromPage is made attempting to read one more value than there actually exists.

**Comment by benjaminwinger** [comment]
I think it's an issue with the VarListNodeColumn offsets not being updated correctly when the new entry is added.

I get the following trace with gdb. Note that the endOffsetInGroup is 0, so later the number of values being set to as non null underflows and becomes very large.
```
#0  0x000055555595a3ee in std::__fill_a1<unsigned long*, unsigned long> (__first=0x77ffdb4bd000, __last=0x77fff8001380,
    __value=@0x5555572f6418: 0) at /usr/include/c++/11/bits/stl_algobase.h:924
#1  0x000055555595812d in std::__fill_a<unsigned long*, unsigned long> (__first=0x77ffd8001388, __last=0x77fff8001380,
    __value=@0x5555572f6418: 0) at /usr/include/c++/11/bits/stl_algobase.h:969
#2  0x0000555555955ebc in std::fill<unsigned long*, unsigned long> (__first=0x77ffd8001388, __last=0x77fff8001380,
    __value=@0x5555572f6418: 0) at /usr/include/c++/11/bits/stl_algobase.h:999
#3  0x0000555555be8f3e in kuzu::common::NullMask::setNullRange (nullEntries=0x77ffd8001380, offset=14,
    numBitsToSet=4294967282, isNull=false) at ../../../../src/common/null_mask.cpp:114
#4  0x0000555555be8e36 in kuzu::common::NullMask::setNullFromRange (this=0x77ffdb4479b0, offset=14,
    numBitsToSet=4294967282, isNull=false) at ../../../../src/common/null_mask.cpp:103
#5  0x00005555559feb98 in kuzu::common::ValueVector::setRangeNonNull (this=0x77ffd9a5d480, startPos=14, len=4294967282)
    at ../../../../../src/include/common/vector/value_vector.h:41
#6  0x0000555556530cc7 in kuzu::storage::NullNodeColumn::scan (this=0x5555582ddb90, transaction=0x77ffdb43c0a0,
    nodeGroupIdx=0, startOffsetInGroup=14, endOffsetInGroup=0, resultVector=0x77ffd9a5d480, offsetInVector=14)
    at ../../../../../src/storage/store/node_column.cpp:177
#7  0x00005555565561f9 in kuzu::storage::StringNodeColumn::scan (this=0x5555582dd820, transaction=0x77ffdb43c0a0,
    nodeGroupIdx=0, startOffsetInGroup=14, endOffsetInGroup=0, resultVector=0x77ffd9a5d480, offsetInVector=14)
    at ../../../../../src/storage/store/string_node_column.cpp:38
#8  0x000055555657e846 in kuzu::storage::VarListNodeColumn::scanFiltered (this=0x5555582dd110,
    transaction=0x77ffdb43c0a0, nodeGroupIdx=0, resultVector=0x77ffd9a5fe00, listOffsetInfoInStorage=...)
    at ../../../../../src/storage/store/var_list_node_column.cpp:131
#9  0x000055555657e223 in kuzu::storage::VarListNodeColumn::scanInternal (this=0x5555582dd110,
    transaction=0x77ffdb43c0a0, nodeIDVector=0x77ffd8024f10, resultVector=0x77ffd9a5fe00)
    at ../../../../../src/storage/store/var_list_node_column.cpp:76
#10 0x0000555556525378 in kuzu::storage::NodeColumn::scan (this=0x5555582dd110, transaction=0x77ffdb43c0a0,
    nodeIDVector=0x77ffd8024f10, resultVector=0x77ffd9a5fe00) at ../../../../../src/storage/store/node_column.cpp:309
```

**Comment by acquamarin** [comment]
```
[2024-04-16 11:24:13.942] [info] DEBUG LOG: 
[2024-04-16 11:24:13.943] [info] QUERY: BEGIN TRANSACTION
[2024-04-16 11:24:13.944] [info] DEBUG LOG: 
[2024-04-16 11:24:13.944] [info] QUERY: CREATE (:person {ID:11, workedHours:[1,2,3], usedNames:['A', 'this is a long name']})
[2024-04-16 11:24:13.984] [info] DEBUG LOG: 
[2024-04-16 11:24:13.984] [info] QUERY: MATCH (a:person) WHERE a.ID > 8 RETURN a.ID, a.workedHours,a.usedNames
unknown file: Failure
C++ exception with description "Assertion failed in file "/Users/z473chen/Desktop/code/kuzu/src/storage/store/list_column.cpp" on line 32: pos < sizeColumnChunk->getNumValues()" thrown in the test body.
```
Now, it causes an assertion failure instead.

**Comment by andyfengHKU** [comment]
This has been fixed.
