### ISSUE TITLE
Bug: Reading from CSV doesn't work due to two double quotes

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#3612]
### Kùzu version

0.4.3dev27

### What happened?

The CSV reader is more picky and fails in cases where pandas and polars are successful. I'll issue more of these sorts of bugs/unexpected behaviours as I find them.

I think our CSV load behaviour should be as reliable (as far as possible) as the conventional methods like Pandas and Polars.

### CSV file

Say we have this in `test.csv`
```
id,test
1,"Some sample text."
2,"Some more sample ""text""."
```

### Pandas ✅

```py
import pandas as pd

pd_df = pd.read_csv("test.csv")
print(pd_df.head())
```
This reads successfully and provides this output.
```
   id                      test
0   1         Some sample text.
1   2  Some more sample "text".
```

### Polars ✅

```py
import polars as pl

pl_df = pl.read_csv("test.csv")
print(pl_df.head())
```
This also reads successfully.

```
shape: (2, 2)
┌─────┬──────────────────────────┐
│ id  ┆ test                     │
│ --- ┆ ---                      │
│ i64 ┆ str                      │
╞═════╪══════════════════════════╡
│ 1   ┆ Some sample text.        │
│ 2   ┆ Some more sample "text". │
└─────┴──────────────────────────┘
```

### Kùzu ❌

This fails to read using `LOAD FROM`.

```py
import shutil
import kuzu

shutil.rmtree("./test", ignore_errors=True)
db = kuzu.Database("./test")
conn = kuzu.Connection(db)

res = conn.execute("LOAD FROM 'test.csv' (header=true) RETURN *").get_as_pl()
print(res)
```
Error:
```
Traceback (most recent call last):
  File "/Users/prrao/code/kuzu-debug/tt.py", line 16, in <module>
    res = conn.execute("LOAD FROM 'test.csv' (header=true) RETURN *").get_as_pl()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/prrao/code/kuzu-debug/.venv/lib/python3.11/site-packages/kuzu/connection.py", line 130, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Copy exception: Error in file test.csv on line 3: quote should be followed by end of file, end of value, end of row or another quote.
```

### Are there known steps to reproduce?

Using the latest dev build of Kùzu and the following packages.
```
pip install --pre kuzu
pip install polars pyarrow pandas
```

**Comment by acquamarin** [comment]
Actually, this is because of the default configurations of our csv reader.
Our default escape character is `\` while duckdb's default escape character is `"`
To load the csv file, you may have to set the default escape character to `"`(the same as duckdb):
```
kuzu> load from '/tmp/test.csv'(header=true,  escape='"') return *;
---------------------------------
| id | test                     |
---------------------------------
| 1  | Some sample text.        |
---------------------------------
| 2  | Some more sample "text". |
---------------------------------
(2 tuples)
(2 columns)
Time: 0.24ms (compiling), 0.34ms (executing)
```

**Comment by prrao87** [comment]
Why isn't our default behaviour the same as DuckDB's in this case?

**Comment by prrao87** [comment]
The following code shows the difference in usability (it's hard for the user to know what to do when they get the CSV read error):

```py
import shutil
import duckdb
import kuzu

shutil.rmtree("./test", ignore_errors=True)
db = kuzu.Database("./test")
kuzu_conn = kuzu.Connection(db)

res = kuzu_conn.execute("""LOAD FROM 'test.csv' (header=true, escape='"') RETURN *""")
print(res.get_as_pl())

duck_donn = duckdb.connect(database=':memory:')
res2 = duck_donn.execute("""SELECT * FROM 'test.csv')""")
print(res2.pl())
```

Result:

```
shape: (2, 2)
┌─────┬──────────────────────────┐
│ id  ┆ text                     │
│ --- ┆ ---                      │
│ str ┆ str                      │
╞═════╪══════════════════════════╡
│ 1   ┆ Some sample text.        │
│ 2   ┆ Some more sample "text". │
└─────┴──────────────────────────┘
shape: (2, 2)
┌─────┬──────────────────────────┐
│ id  ┆ text                     │
│ --- ┆ ---                      │
│ i64 ┆ str                      │
╞═════╪══════════════════════════╡
│ 1   ┆ Some sample text.        │
│ 2   ┆ Some more sample "text". │
```

Both work, but the DuckDB version just "works", and the Kùzu version is harder to read and reason about.

**Comment by acquamarin** [comment]
ok, will open a PR to change the default csv settings.

**Comment by andyfengHKU** [comment]
Default changed in #3639
