### ISSUE TITLE
Bug: Can not update node properties: write-write conflict in Auto transaction.

### ISSUE THREAD

**Issue by Claus1** [kuzudb/kuzu#4056]
### Kùzu version

0.5.0

### What operating system are you using?

Ubuntu 22

### What happened?

I send queries for updating a property when typing in UI from single-threaded python code:
MATCH (a: User) WHERE a.ID = 4 SET a.name = "something"
The first query executes ok, but all next queries raise Runtime exception: Write-write conflict of updating the same row.

### Are there known steps to reproduce?

Update any node property more than once.

**Comment by prrao87** [comment]
I just tried this code in Python and yep, it seems to be happening if you try to update the node more than once (happens at the second occurrence).

@ray6080, could you take a look when possible?

```py
import kuzu
import shutil

shutil.rmtree("test_db", ignore_errors=True)
db = kuzu.Database("test_db")
conn = kuzu.Connection(db)

# create a table
conn.execute("CREATE NODE TABLE IF NOT EXISTS Product (item STRING, price INT64, PRIMARY KEY (item))")

# insert some data
conn.execute("CREATE (n:Product {item: 'watch'}) SET n.price = 100")

# Check values
print(conn.execute("MATCH (n:Product) RETURN n.item, n.price").get_as_df())

# Match a node and update its values
conn.execute("MATCH (n:Product) WHERE n.item = 'watch' SET n.price = 200")

# Check values
print(conn.execute("MATCH (n:Product) RETURN n.item, n.price").get_as_df())

# Match a node and update its values
conn.execute("MATCH (n:Product) WHERE n.item = 'watch' SET n.price = 300")

# Check values
print(conn.execute("MATCH (n:Product) RETURN n.item, n.price").get_as_df())
```
Result:
```
  n.item  n.price
0  watch      100
  n.item  n.price
0  watch      200
Traceback (most recent call last):
  File "/Users/prrao/code/kuzu-debug/t.py", line 24, in <module>
    conn.execute("MATCH (n:Product) WHERE n.item = 'watch' SET n.price = 300")
  File "/Users/prrao/code/kuzu-debug/.venv/lib/python3.12/site-packages/kuzu/connection.py", line 130, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Runtime exception: Write-write conflict of updating the same row.
```

**Comment by ray6080** [comment]
Will take a look soon! Thanks for reporting!
