### ISSUE TITLE
Support Decimal data type when scanning and copying from RDBMS tables

### ISSUE THREAD

**Issue by prrao87** [kuzudb/kuzu#4319]
### API

Other

### Description

For monetary values, the Decimal value is required in many use cases. We should support scanning/copying columns that have the `DECIMAL` type from DuckDB, Postgres and other relational databases.

Here's an example table I have in DuckDB:
```
┌────────────────┬───────────┬─────────────┬───────────────┬─────────────────────┬─────────────┐
│ transaction_id ┆ client_id ┆ merchant_id ┆ amount        ┆ timestamp           ┆ is_disputed │
│ ---            ┆ ---       ┆ ---         ┆ ---           ┆ ---                 ┆ ---         │
│ str            ┆ str       ┆ str         ┆ decimal[10,2] ┆ datetime[μs]        ┆ bool        │
╞════════════════╪═══════════╪═════════════╪═══════════════╪═════════════════════╪═════════════╡
│ t1             ┆ c327      ┆ m46         ┆ 754.41        ┆ 2023-03-10 23:48:23 ┆ false       │
│ t2             ┆ c767      ┆ m96         ┆ 1348.25       ┆ 2023-06-17 12:59:13 ┆ false       │
│ t3             ┆ c9        ┆ m68         ┆ 392.47        ┆ 2024-01-06 00:51:39 ┆ false       │
│ t4             ┆ c325      ┆ m94         ┆ 166.16        ┆ 2023-03-09 11:29:55 ┆ false       │
│ t5             ┆ c336      ┆ m74         ┆ 265.23        ┆ 2023-06-19 14:12:17 ┆ false       │
│ t6             ┆ c287      ┆ m62         ┆ 229.80        ┆ 2023-12-16 09:36:57 ┆ false       │
│ t7             ┆ c373      ┆ m95         ┆ 485.03        ┆ 2023-12-01 03:18:00 ┆ false       │
│ t8             ┆ c836      ┆ m11         ┆ 461.53        ┆ 2023-07-18 10:31:38 ┆ false       │
│ t9             ┆ c821      ┆ m8          ┆ 71.62         ┆ 2023-02-28 04:29:30 ┆ false       │
│ t10            ┆ c537      ┆ m63         ┆ 1481.45       ┆ 2023-10-29 11:39:39 ┆ false       │
└────────────────┴───────────┴─────────────┴───────────────┴─────────────────────┴─────────────┘
```

This is the error I get when trying to copy from it in Kùzu.
```
Traceback (most recent call last):
  File "/Users/prrao/code/tutorials/src/video_6/ingest_kuzu.py", line 59, in <module>
    conn.execute("ATTACH 'ex_db_duckdb.duckdb' AS tx (dbtype duckdb)")
  File "/Users/prrao/code/tutorials/src/video_6/.venv/lib/python3.12/site-packages/kuzu/connection.py", line 130, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Binder exception: Unsupported duckdb type: DECIMAL(10,2).
```

**Comment by andyfengHKU** [comment]
This should be fixed in #4326
