### ISSUE TITLE
Support prepared statements for CALL function

### ISSUE THREAD

**Issue by ray6080** [kuzudb/kuzu#4592]
### API

Python

### Description

```
>>> res = conn.execute(
...         """
...         CALL QUERY_HNSW_INDEX('tbl_hnsw_index', 'tbl', $qvec, 100) return *
...         """,
...         parameters={"qvec": a})
Traceback (most recent call last):
  File "<python-input-10>", line 1, in <module>
    res = conn.execute(
            """
            CALL QUERY_HNSW_INDEX('tbl_hnsw_index', 'tbl', $qvec, 100) return *
            """,
            parameters={"qvec": a})
  File "/Users/guodong/Developer/kuzu/tools/python_api/build/kuzu/connection.py", line 133, in execute
    _query_result = self._connection.execute(prepared_statement._prepared_statement, parameters)
RuntimeError: Binder exception: $_2_ has type PARAMETER but LITERAL was expected.
```

**Comment by acquamarin** [comment]
solved in #4628
